### ISSUE TITLE
CAMARA Consent Management Guideline: SimSwap 

### ISSUE THREAD

**Issue by psidana1983** [camaraproject/SimSwap#84] opened 2023-12-21 11:37 UTC
Hi Team , 

I am working on securing the CAMARA certification for SIM Swap API and as per the input I have received it is mandatory to implement 3 Legged authorization , which requires CIBA flow . I have below questions regarding this flow :

1.  Who should give this consent,  is it by the customer to a telecom operator ( flow is end user -> bank -> Teleco operator) or the end user whos information is getting shared. As per our understanding , the consent should be done between the end user and bank , not between end user and teleco operator.
 
3. When should we take this consent , is it while onboarding the customer or before providing the access to an API.  
4. What should be the frequency of this consent
5. For how long this consent should be valid
6. What is basis on which CAMARA has decided to implement CIBA flow for SIM Swap . Is there any data privacy guidelines or policies getting followed , like GDPR . 

Regards
Prashant Sidana

**Comment by HuubAppelboom** [comment] 2023-12-27 15:15
All cases we have implemented so far in the Netherlands have "Legitimate Interest" as a legal basis, and not on "User Consent", and I believe in many European markets this is the case (there may be some markets where User Consnet is required, but usually this is not the same User Consent as is defined under the GDPR.
.
User Consent as is defined under GDPR is not really suitable for anti-fraud cases, because the User Consent needs to be freely given, where the choice of the user must not have consequences like whether he can or cannot use (for example) a banking service.  Also, the user should always be able to withdraw consent just as eastily as it is given.  For SIM swap scenarios this implies that the fraudsetr would be able to withdraw the consent immediately after activation of the SIM, so this would make the SIM Swap service useless. In what cases would you then use User Consent under the GDPR ? For example when you can susbcrive to a newsletter or information from partners of a supplier etc. But probably never in a fraud case where the fraudster can manipulate the given consent to avoid detection.

With Legitimate Interest, you rely on the Legitimate Interest of a 3rd party, for example a bank. It is never the legitimate interest of the MNO, because the damage caused by SIM swap fraud does not impact the MNO itself.  In these case the bank has to evaluate the privacy interests of its customers versus the impact of potential fraud. If the fraud impact outweighs the privacy risk, and there is no suitable less privacy invasive alternative, then the bank can decide to choose Legitimate Interest as a legal basis.  And the MNO can decide whether they will accept/ agree with the decision of the bank.

**Comment by HuubAppelboom** [comment] 2023-12-27 15:34
On a side note: in case you do think User Consent is required, please note that under the GDPR any User Consent must always acquired before any personal data is being processed.  With the SIM Swap flow, the first data that gows form the bank to the mno is the MSISDN, so the consent must always be collected by the bank (otherwise they don't comply with the GDPR when they send the MSISDN). Storage of the consent can be done by either party, the MNO or the bank. I think CAMARA currently does not support such a process yet, as far as I have seen.

**Comment by psidana1983** [comment] 2023-12-29 06:09
Hi Thanks for the details information  . 
So based on above explanation , I have understood that for SIM Swap consent is required between the end user and the bank, MNO has nothing to do with it . Correct?

As per my understanding for CAMARA certification is it mandatory to implement 3 legged -CIBA - authorization . Is this correct?

Regards
Prashant Sidana

**Comment by HuubAppelboom** [comment] 2023-12-29 14:03
@psidana1983  No,  under the GDPR user consent and legitimate interest are 2 different legal basis that you can use for the processing of personal data.

- In case of legimate interest (of the bank) as  a legal basis, the bank or the MNO does not have to ask the user separately for permission (with a separate tick box); you do however need to mention the processing in the T&C or Privacy Policy (to which the user will have to consent to use the service; so SIM Swap is always included in the service).

- In case of user consent as a legal basis, the bank (or MNO) will have to ask the user separately whether they agree to the checking of the SIM activation date. In case the user denies, the user must still be able to use the banking service (it is a principle of free choice).

Al cases that I know of work with legitimate interest, at least in the Netherlands.  The only thing the bank needs to do is mention in their privacy policy that this kind of data processing takes place (and the MNO should also mention it, in general terms in their privacy policy). So you don't see a separate tick box that users can choose.

Not sure about the CIBA authorization, but for legitimate interest cases it does not make sense to me.

@DT-DawidWroblewski  Dawid, can you comment on this matter ?

**Comment by gregory1g** [comment] 2024-01-02 06:20
my 5c:

>For SIM swap scenarios this implies that the fraudster would be able to withdraw the consent immediately after activation of the SIM, so this would make the SIM Swap service useless.

Not really, if the fraudster withdraw the context, SIM Swap will return a error and bank will not process the operation.

> "Legitimate Interest" as a legal basis
This could a good enough from the legal point of view, still many privacy focused people try to avoid exactly the scenario you have described because "legitimate Interest" is the most "flexible" way to collect and share data.

@HuubAppelboom, a question - do I understand correctly that in the Netherlands you secure valid SimSwap API usage via a contract bentween MNO and ASP? Like if a bank invokes SimSwap for a person who is not a customer of this bank, the bank breaks the conditions of the contract with the MNO.

**Comment by gregory1g** [comment] 2024-01-02 06:24
@psidana1983 

for cases when user consent is required:

> So based on above explanation , I have understood that for SIM Swap consent is required between the end user and the bank, MNO has nothing to do with it . Correct?

A user gives a consent to the MNO to share their information with the bank. Consent is collected, stored (and later validated) by MNO. 

> As per my understanding for CAMARA certification is it mandatory to implement 3 legged -CIBA - authorization . Is this correct?

afaik, Camara requires 3-legged auth, but not necessarily CIBA, front-end flow can be used as well.

**Comment by HuubAppelboom** [comment] 2024-01-02 08:15
@gregory1g 
There is an important principle for user consent in the GDPR, and that is the consent needs to be freely given. This means that you can not tie a reward or a punishment as a consequence to the consent.  For example, you can not give customer a discount when you ask them for consent to share data with 3rd parties.  Also, this means that you can not deny access to a banking service when the user withdraws his consent (which would happen in case of a sim swap fraud).

Fraud prevention is exactly one of the reasons why legitimate interest exsists in the first place, see the example mentionned by the European Commision on this page:
[https://commission.europa.eu/law/law-topic/data-protection/reform/rules-business-and-organisations/legal-grounds-processing-data/grounds-processing/what-does-grounds-legitimate-interest-mean_en](url)

To have Legitimate Interest as a valid legal basis, the parties involved need to do an extensive Data Privacy Impact Assesment, in which is being considered whether it is allowed or not.  An important aspect in this is the question what outweighs what, the privacy impact of the processing versus the legitimate interest of the bank. There are important questions to answer here, like whether less privacy invasive alternatives exsist, whether the user can expect the processing to occur, what is the impact if the processing does not happen, what is the purpose of the processing, etc. If the outcome of the DPIA is negative, you have no legal basis for the processing, and you can not proces the data.

**Comment by HuubAppelboom** [comment] 2024-01-02 08:29
@gregory1g  In the case of legitimate interest, the bank has to be transparent to the end user what the data they collect for is being used for, so they need to put this in their privacy policy.  And so does the telco, that they enable thid kind of fraud prevention.

With the contracts the MNO have with banks, the MNO (or the Aggregators) typically demand that the bank can use SIM swap data points only for fraud prevention, and that the bank needs to perform a DPIA to show that legitimate interest can be applied. The MNO asks the bank during the onboarding of the service documented evidence (like their privacy imact assesment, and links towards the sections in the privacy statement) etc that they fully comply with the GDPR, so that users are informed, that there is way to object against the processing, etc, etc.

In cases of user consent, the MNO typically also asks for proof that the user consent is valid:
- whether there are any negative consequences if consent is not given
- whether the consent is acquired separately (from the privacy policy or T&C or any other items)
- whether it is transparent to the user what the consent is about (for exmaple "Do you agree that we use your MSISDN to check your SIM activation date" is not valid, because users don't know what an MSISDN is).
- etc, etc.

**Comment by HuubAppelboom** [comment] 2024-01-02 08:39
@psidana1983 As far as I am aware there is no need for SIM Swap to implement a 3 legged flow. In many use cases the device of the user is not involved in the flow, so why would this be a requirement ???

**Comment by gregory1g** [comment] 2024-01-02 08:39
@HuubAppelboom 
Thank you for the detailed clarification.

One question: you say the bank cannot deny access to banking service if a consent is revoked.  To use my online banking I should install 2FA app on my smartphone and give it some permissions, if I revoke permissions for the app, my transaction will not happen. is that deny to bank services?

SimSwap protects OTP, in case of consent revoke bank can suggest alternative mechanism (from installing an app to  visit its office), right?

This makes me think that depending on local legal requirements and MNO wishes/proposition,  either "legitimate Interest" or "user consent" approaches can be used for SimSwap, but as you mentioned, majority of MNOs, probably will prefer "legitimate Interest"

**Comment by gregory1g** [comment] 2024-01-02 08:43
> @psidana1983 As far as I am aware there is no need for SIM Swap to implement a 3 legged flow. In many use cases the device of the user is not involved in the flow, so why would this be a requirement ???

This was discussed several times I guess and there are different view. BTW, 3-legged does not need to be interactive during every invocation.

Topics discussed in this issue can be discussed in the next meeting - it will be great if you could join, @HuubAppelboom !

**Comment by HuubAppelboom** [comment] 2024-01-02 08:54
@gregory1g   For a discussion about user consent, see for example this web page. Here you will find a lot of details you need to comply with for user consent:

[https://gdpr-info.eu/issues/consent/](url)

As soon as the consent is revoked, you can not verify the SIM anymore, and then you have to consider that the bank must use a strong authentication method.   If you offer alternatives, they need to be at least as easy to use (visiting an office is hardly an alternative), and that it does not force people.  Some people don;t have (or don't want to use) a smartphone, so that is also not 
always a valid alternative.  And for cases where you want to detect whether the SIM swap fraudster is calling with the bank, I don't see an alternative either.

**Comment by psidana1983** [comment] 2024-01-03 07:55
Thanks @gregory1g  and @HuubAppelboom  for the detailed discussion on this point 

So what I have understood from the discussion here is :
1.  It is not clear, if it is mandatory to implement 3 Legged authorization for CAMARA certification . This point is still in discussion and can be clarified in discussion. Can you share me the meeting invite , I can join to discuss it further
2. If required, we can implement both CIBA or front end flow for 3 Legged authorization  . Correct

**Comment by gregory1g** [comment] 2024-01-05 06:58
> And for cases where you want to detect whether the SIM swap fraudster is calling with the bank, I don't see an alternative either.

banks normally allow people to use any phone line to calling them. In this case  a common approach is asking for dedicated hotline password which user created during onboarding. The same approach can be used if SimSwap check failed for whatever reason (from revoked consent to the technical issues in the given MNO API infrastructure).

**Comment by HuubAppelboom** [comment] 2024-01-05 07:49
> banks normally allow people to use any phone line to calling them. In this case a common approach is asking for dedicated hotline password which user created during onboarding. The same approach can be used if SimSwap check failed for whatever reason (from revoked consent to the technical issues in the given MNO API infrastructure).

In case it is the other way around, the bank calling the customer because they detect strange activity the account, you would like to see whether a SIM swap has taken place before you make the outgoing call.  Hotline passwords are not that common here, because most of the interaction is done online.

**Comment by gregory1g** [comment] 2024-01-05 08:13
even in this case there are alternatives. The client does not have to have a mobile phone,  the phone can be stolen etc.
hotline password is one the simwap alternatives for voice based contacts, for online banking there are others.

This just shows that legitimate interest is not the only possible way to exposure simswap.

**Comment by gregory1g** [comment] 2024-01-05 08:37
if you already know that this person is a fraudster - yes, this is rather useless.

in many cases a person in charge asks if they may see your id document (to compare photo there with you) - similar thing.

A bank can request a consent when a client activates online banking and then just use it. If user opted-out later, alternatives mechanisms to validate operation was really initiated by the client.

**Comment by psidana1983** [comment] 2024-01-10 05:22
@gregory1g 
Thanks for the input shared. 
I have last question , I understand 3 Legged can be implemented using front end flow ( Authorization code flow)  or CIBA flow but
     1. We are not sure what channel -  Online through APP or offline through customer care over call - is bank using to interact with the end users so how can be decide what to implement beforehand.  
Different banks may have different ways of interaction so I feel creating dependency on 3 legged implementation for certification is not justifiable . What is your opinion on it. 

2.  In both the cases front end flow or CIBA flow whom shall we authenticate , end user or the bank and for authenticate we have to force them to register as a user in MNO system. correct?  

Regards
Prashant Sidana

**Comment by psidana1983** [comment] 2024-02-09 07:40
@gregory1g  @HuubAppelboom 

In the front end flow , I have to force my clients to update their customer journey to which they may or may not agree . 

and in the CIBA flow, it will not add value since in the SIM Swap fraud, an unauthorized user has already compromised the end-user’s SIM to get the OTP SMS, sending another OTP will not add any value.

Considering above I would like to suggest to not make authorization as a mandatory step for certification . 

Please suggest.

**Comment by HuubAppelboom** [comment] 2024-02-09 07:56
In addition, CIBA flow may remain much slower than client credentials. It wouldn't surprise me when most parties will keep using client credentials for SIM Swap.

**Comment by DT-DawidWroblewski** [comment] 2024-03-14 14:14
Hi!

Issue combined with #89 

Issue concluded - closing.

Discussion has to continue inside [commonalities](https://github.com/camaraproject/WorkingGroups/tree/main/Commonalities).

Thx!

**Closed** 2024-03-14 14:25 UTC
